version: '3.8'
services:
  shell:
    build:
      context: .
      dockerfile: packages/shell/Dockerfile
    ports:
      - "5000:80"
  dashboard:
    build:
      context: .
      dockerfile: packages/dashboard/Dockerfile
    ports:
      - "5001:80"
  profile:
    build:
      context: .
      dockerfile: packages/profile/Dockerfile
    ports:
      - "5002:80"
